# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fae64b107f825a8521cd5ff937ea13206557d3f6ad7157eace18fc69d0e810a01bad3103a7ff993bbd4ef53abb5dbd0a0352726e0802d45b9c32e94850673c30

test:
  secret_key_base: a2e44c2361950486b17dedfdc56c1a1a7fe124488245391182c0b79a54e0680e9142a73a7bafd6eee07c75dd7d65f90f51f67865561c96e8f8858d461c34e3f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
